---
- hosts: control
  vars:
    download_url: http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jdk-8u144-linux-x64.tar.gz
    download_folder: /opt
    java_name: "{{download_folder}}/jdk1.8.0_144"
    java_archive: "{{download_folder}}/jdk-8u144-linux-x64.tar.gz"
    java_unzip: "{{download_folder}}/jdk-8u144-linux-x64.tar"
 
 
  tasks:
  - name: Download Java
    get_url:
       url: "{{ download_url }}"
       headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
       dest: "{{ java_archive }}"

  - name: Unzip archive
    unarchive:
       src={{java_archive}}
       dest={{download_folder}}
       copy=no

  - name: Unpack archive
    command: "tar -zxvf {{java_unzip}} -C {{download_folder}} creates={{java_name}}"
 
  - name: Fix ownership
    file: state=directory path={{java_name}} owner=root group=root recurse=yes
 
  - name: Make Java available for system
    command: 'alternatives --install "/usr/bin/java" "java" "{{java_name}}/bin/java" 2000'

- hosts: mseries
  vars:
    download_folder: /opt
    java_name: "{{download_folder}}/jdk1.8.0_144"
    java_archive: "{{download_folder}}/jdk-8u144-linux-x64.tar.gz"
    java_unzip: "{{download_folder}}/jdk-8u144-linux-x64.tar"

  tasks:
  - name: Copy EPEL RPM from x1 host to remote mseries servers
    copy:
       src={{ java_archive }}
       dest={{ java_archive }}

  - name: Unzip archive
    unarchive:
       src={{java_archive}}
       dest={{download_folder}}

  - name: Unpack archive
    command: "tar -zxvf {{java_unzip}} -C {{download_folder}} creates={{java_name}}"

  - name: Fix ownership
    file: state=directory path={{java_name}} owner=root group=root recurse=yes

  - name: Make Java available for system
    command: 'alternatives --install "/usr/bin/java" "java" "{{java_name}}/bin/java" 2000'

  - name: Clean up
    file: state=absent path={{java_archive}}

- hosts: nseries
  vars:
    download_folder: /opt
    java_name: "{{download_folder}}/jdk1.8.0_144"
    java_archive: "{{download_folder}}/jdk-8u144-linux-x64.tar.gz"
    java_unzip: "{{download_folder}}/jdk-8u144-linux-x64.tar"

  tasks:
  - name: Copy EPEL RPM from x1 host to remote mseries servers
    copy:
       src={{ java_archive }}
       dest={{ java_archive }}

  - name: Unzip archive
    unarchive:
       src={{java_archive}}
       dest={{download_folder}}

  - name: Unpack archive
    command: "tar -zxvf {{java_unzip}} -C {{download_folder}} creates={{java_name}}"

  - name: Fix ownership
    file: state=directory path={{java_name}} owner=root group=root recurse=yes

  - name: Make Java available for system
    command: 'alternatives --install "/usr/bin/java" "java" "{{java_name}}/bin/java" 2000'

  - name: Clean up
    file: state=absent path={{java_archive}}
