---
   - hosts: all
     tasks:
        - name: Install mandatory packages
          yum: pkg={{item}} state=installed
          with_items:
             - git
             - mlocate
             - ntp
