---
   - hosts: mseries
     tasks:
        - name: Shutdown all mseries servers
          command: shutdown -P now
   - hosts: nseries
     tasks:
        - name: Shutdown all nseries servers
          command: shutdown -P now
